### ISSUE TITLE
Add or edit your own text adventure games! (Hacktoberfest 2019)

### ISSUE THREAD

**Issue by D4rk3l** [D4rk3l/interactive-text-games-hacktoberfest#1]
Please check the README.md for more information on how to contribute!
This is a great place to start for coding beginners - feel free to edit others' code or add your own!

**Comment by vickywane** [comment]
any sample text adventure  game ?

**Comment by k1dnyy** [comment]
I have no idea what to write but I will try!

**Comment by alidaghighi** [comment]
To be honest I liked this idea and, I want to write another one :D
