### ISSUE TITLE
Can we make PR for hacktoberfest? Also should the text game be only in python?

### ISSUE THREAD

**Issue by blasttrash** [D4rk3l/interactive-text-games-hacktoberfest#14]
1) I am wondering if I can contribute to this repo for hacktoberfest?
2) Also should the text game be only in python? Can I use other languages like say js or java?

Thanks

**Comment by D4rk3l** [comment]
Hi!
Yes, contributing to this repo will count towards Hacktoberfest.
You are allowed to use any language you want, not just Python scripts! Java/JavaScript is fine too.
Thanks for asking, I'm happy to clear this up
